sname:               day23-haskell
version:             0.1.0.0
github:              "githubuser/day23"
license:             MIT
author:              "Xavier CLEMENCE"
maintainer:          "example@example.com"
copyright:           "2021 Xavier CLEMENCE"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/day23#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- time
- primitive

library:
  source-dirs: src

executables:
  day23-haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day23-haskell

tests:
  day23-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day23-haskell
